Sladim 172 unit tests
ccims/paymentsystem-service pull request #12
Opened 2020-09-11 14:29 UTC by KaiBraun

## Preparations
Please check if the PR fulfills these requirements
- [ ] Readme (How to Install, Run, Use and Configure) wurde aktualisiert falls nötig
- [ ] Das Feature ist dokumentiert
- [ ] Alle nicht getter und setter Methoden sind dokumentiert
- [ ] Es wurden Unit tests für neue Features erstellt
- [ ] Alle Tests müssen erfolgreich sein
- [ ] Mindestens ein Reviewer muss den Pull Request akzeptieren

## :ticket: Description

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Docs  update and unit tests

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

## :lock: Closes
Which issue(s) is (are) being closed by the PR?

2020-09-12 06:19 UTC, stiesssh requested changes

2020-09-12 06:19 UTC, stiesssh commented on README.md
> +For a more detailed description of all functionalities visit the the Price Service section of out [Github Pages Documentation](https://ccims.github.io/overview-and-documentation/price-service).
```suggestion
For a more detailed description of all functionalities visit the Price Service section of our [Github Pages Documentation](https://ccims.github.io/overview-and-documentation/price-service).
```

2020-09-12 06:19 UTC, stiesssh commented on README.md
> +For a more detailed description of all functionalities visit the the Price Service section of out [Github Pages Documentation](https://ccims.github.io/overview-and-documentation/price-service).
```suggestion
For a more detailed description of all functionalities visit the Price Service section of our [Github Pages Documentation](https://ccims.github.io/overview-and-documentation/price-service).
```

2020-09-12 06:19 UTC, stiesssh commented on README.md
> +The backend listens at http://localhost:3300/request for the incoming default GET requests and automatically transfers them to backend of database service (usually sitting ad http://localhost:3000 wh
```suggestion
The backend listens at http://localhost:3300/request for the incoming default GET requests and automatically transfers them to the backend of the database service (usually sitting at http://localhost:3000 when running). 
```

2020-09-12 06:19 UTC, stiesssh commented on priceservice/src/app.controller.ts
> +   * @returns the value received from the database service or an error if request was not succesful for any reason (like timeout or CB open).
leerzeile zwischen fließtext und tags.
zeilenumbruch, wenn die zeile zu lang (bei uns m.e. mehr als 140 zeichen) wird.

2020-09-12 06:19 UTC, stiesssh commented on priceservice/src/app.controller.ts
> +   * Could also return a different value if database service is configured to sen d semantically false responses
```suggestion
   * Could also return a different value if database service is configured to send semantically false responses  
```

2020-09-12 06:19 UTC, stiesssh commented on priceservice/src/app.controller.ts
> +   * @returns  A promise with the balance received from the database service or an error if request was not succesful for any reason.
missing blank line & typo
```suggestion
   * Handles get requests to receive balance from database service
   *
   * @returns  A promise with the balance received from the database service or an error if request was not successful for any reason. 
```

2020-09-12 06:19 UTC, stiesssh commented on priceservice/src/app.controller.ts
> +   * Could also return a different value if database service is configured to sen d semantically false responses
```suggestion
   * Handles get requests to receive customer name from database service
   *
   * @returns a Promise with the customer name received from the database service or an error if request was not successful for any reason 
   * Could also return a different value if database service is configured to send semantically false responses
```

2020-09-12 06:19 UTC, stiesssh commented on priceservice/src/app.controller.ts
>     * bind to this router handler that will throw a timeout exception after 5 seconds.
außerdem: unklarer satzbaut. bezieht sich der nebensatz ("that will throw...") auf den interceptor oder auf den router handler? 
```suggestion
   * will be transferred to the database service. A timeout interceptor is also
   * bound to this router handler that will throw a timeout exception after 5 seconds.
```

2020-09-12 06:19 UTC, stiesssh commented on priceservice/src/app.service.spec.ts
> +  it('should thow Http Excpetion due to Circuit Breaker open', async () => {
```suggestion
  it('should throw Http Excpetion due to Circuit Breaker open', async () => {
```

2020-09-12 06:19 UTC, stiesssh commented on priceservice/src/app.service.spec.ts
> +
eigentlich sind die beiden operationen `handleTimeout` und `sendRequest` durch die vorhandenen testfälle bereits abgedeckt, da sie von der operation `handleRequest` genutzt werden, d.h. ein erfolgreicher test von `handleRequest` impliziert, dass auch `handleTimeout` und `sendRequest`korrekt sind.

es ist dennoch sinnvoll `handleTimeout` und `sendRequest` einzeln zu testen, und zwar aus folgendem grund:
wenn einer der test für `handleRequest` fehl schlägt, ist nicht sofort ersichtlich, an welcher stelle er fehl schlägt.
wenn zusätzlich test für `handleTimeout` und `sendRequest` existieren, kann man sofort fest stellen, ob der fehlschlag durch eine dieser beiden operationen verursacht wurde, oder ob der fehler direkt in der `handleRequest` operation zu suchen ist.

2020-09-12 06:24 UTC, stiesssh commented
außerdem habt ihr in der README diesen echt langen code block voller fließtext und stichpunke, was ich persönlich äußerst unangenehm zu lesen finde. mein vorschlag:  formatiert den großen code block am ende der README als normalen text und nutzt den `code style` nur, um die urls und das config format hervorzuheben.

2020-09-15 10:08 UTC, KaiBraun commented on priceservice/src/app.service.spec.ts
> +
Ich habe in die Tests noch Fälle hinzugefügt, die zusätzlich die `handleTimeout` isoliert testet (keine neuen Tests da der Aufbau identisch wäre). `sendRequest` ist leider unmöglich zu testen, da diese Methode einzig dafür da ist eine http request zu schicken und wir dementsprechend diese Methode in jedem Test  mocken müssen um gewünschtes Verhalten zu simulieren.

2020-09-15 10:30 UTC, stiesssh commented on priceservice/src/app.service.spec.ts
> +
kk, klingt sinnvoll.

2020-09-15 10:32 UTC, stiesssh approved these changes

2020-09-15 11:40 UTC, merged