Sladim 104
ccims/paymentsystem-service pull request #7
Opened 2020-07-28 09:18 UTC by JonasJW

## Preparations
Please check if the PR fulfills these requirements
- [x] Readme (How to Install, Run, Use and Configure) wurde aktualisiert falls nötig
- [x] Das Feature ist dokumentiert
- [x] Alle nicht getter und setter Methoden sind dokumentiert
- [ ] Es wurden Unit tests für neue Features erstellt
- [ ] Alle Tests müssen erfolgreich sein
- [ ] Mindestens ein Reviewer muss den Pull Request akzeptieren

## :ticket: Description

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
uses error-format with correlationId for reporting errors to error-monitor

* **What is the current behavior?** (You can also link to an open issue here)
uses log-format for reporting errors to error-monitor

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Other information**:

## :lock: Closes
Which issue(s) is (are) being closed by the PR?

2020-07-28 09:21 UTC, JonasJW commented
Test cases cannot be fixed yet because this service uses `error-format`, that is currently in review

2020-07-28 10:10 UTC, stiesssh requested changes

2020-07-28 10:10 UTC, stiesssh commented on priceservice/src/app.service.ts
> +        throw new HttpException(
m.e. muss die doku noch angepasst werden? 
da heiß es nämlich noch "Otherwise, a log [...] will be created [..] and sent to the error response monitor." während hier Exceptions geworfen werden?

2020-07-29 16:04 UTC, MarcelWolkober approved these changes

2020-07-30 09:15 UTC, stiesssh approved these changes

2020-07-30 14:28 UTC, merged